# workflows to sync certain files when changes are pushed to the main branch
name: Sync Helm Chart README.md

on:
  pull_request_target:
    branches:
      - 'main'
    paths:
      - 'charts/aws-pca-issuer/values.yaml'

env:
  GITHUB_USER_NAME: github-actions
  GITHUB_USER_EMAIL: github-actions@github.com

  sync-helm-chart-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}

          # TODO: Clone this file and only watch the values.yaml path.
          # Basically, Git can automatically check if the file is changed, no need to do it both times.
      - name: Regenerate README if values.yaml is changed
        id: regenerate-readme
        run: |
          echo "Regenerating charts/aws-pca-issuer/README.md since charts/aws-pca-issuer/values.yaml has updated"
          success=$( (make helm-docs && echo true) || echo false)
          if $success; then
            echo "result=success" >> $GITHUB_OUTPUT
          else
            echo "result=fail" >> $GITHUB_OUTPUT
          fi

      - name: Update pull request with new Helm README.md
        if: ${{ steps.regenerate-readme.outputs.result == 'success' }}
        uses: divyansh-gupta/create-or-update-pull-request-action@65a6b01b19b69d7865fcf484340b06548fc02e64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ github.head_ref }}
          path: "."
          commit-message: |
            Sync charts/aws-pca-issuer/README.md in pull-request ${{ github.event.pull_request.number }}

            Signed-off-by: ${{ env.GITHUB_USER_NAME }} <${{ env.GITHUB_USER_EMAIL }}>
          author: "${{ env.GITHUB_USER_NAME }} <${{ env.GITHUB_USER_EMAIL }}>"

      - name: Comment on pull request that the README is updated
        if: ${{ steps.regenerate-readme.outputs.result == 'success' }}
        uses: divyansh-gupta/actions-comment-pull-request@675cdfe1695d33e816e060460a72feafee079d3f
        with:
          message: 'Detected changes in charts/aws-pca-issuer/values.yaml. Updated charts/aws-pca-issuer/README.md and added it as commit to this PR for review.'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Comment on pull request that the README was unable to be updated
        if: ${{ steps.regenerate-readme.outputs.result == 'fail' }}
        uses: divyansh-gupta/actions-comment-pull-request@675cdfe1695d33e816e060460a72feafee079d3f
        with:
          message: 'Detected changes in charts/aws-pca-issuer/values.yaml, but was unable to regenerate charts/aws-pca-issuer/README.md. Please update the pull request with README.md changes by running `make helm-docs` manually and adding the changed README.md to the commit.'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
